@startuml
title Регистрация пользователя

:Начало;

repeat
  :Ввод: логин и пароль;
  backward:Сообщение:\nлогин занят.\nвыберите другой;
repeat while (Такой логин уже существует?) is (да) not (нет)

:Сохранение данных\nпользователя;
:Вывод:\nрегистрация\nвыполнена;

:Конец;
@enduml