@startuml
title Процесс покупки билета

:Начало;

:Ввод: выбор фильма и сеанса;

repeat
  :Вывод: список всех мест на этом сеансе;
backward:нет;
repeat while (Выбранное место свободно?) is ( ) not (да)

:Оформление заказа;

repeat
  :Оплата билета;
backward:нет;
repeat while (Оплата прошла успешно?) is ( ) not (да)

:Фиксация продажи и выдача электронного билета;

:Конец;
@enduml
